version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ./frontend/:/app/:delegated
    # networks:
    #   - mongo-dev-net
    # environment:
    #   database__client: mysql
    #   database__connection__host: db
    #   database__connection__user: root
    #   database__connection__password: YOURDBPASSWORDhere
    #   database__connection__database: ghost

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
      # - mongo2
      # - mongo3
    volumes:
      - /app/node_modules
      - ./backend/:/app/:delegated
    # networks:
    #   - mongo-dev-net
